#!/usr/bin/env bash
set -ev
testdir="$(cd "$(dirname "$0")" && pwd)"
testrun="$testdir/testrun"

CXX="clang++ -std=c++11"
FRAMEWORKS="-framework CoreFoundation -framework Foundation -framework Cocoa"

rm -f "$testrun"

# $CXX $CXXFLAGS $FRAMEWORKS "$testdir/tests.mm" -o "$testrun" 
# "$testrun"
# rm -f "$testrun"

$CXX $CXXFLAGS $FRAMEWORKS "$testdir/tests.cpp" -o "$testrun" 
"$testrun"
rm -f "$testrun"
